development:
  adapter: postgresql
  encoding: unicode
  database: willitrain_development
  pool: 5
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: willitrain_production
  pool: 5
  username:
  password: